language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libav-tools
  - sudo apt-get install -y sox
  - export PYVERSION="$(python --version)"
  - export REGEXVERS="Python 3.4.*"
install:
  - if [[ $PYVERSION =~ $REGEXVERS ]]; then pip install -r requirements3.4.txt; else pip install -r requirements.txt; fi
script:
  - cd ./tests
  - ls
  - python full.py furelise.wav
  - python frames.py stereo_furelise.wav
